using System.Collections.Generic;
using UnityEngine;
using UnityEngine.EventSystems;
using UnityEngine.UI;

namespace Gugarythm
{
    public sealed class SonolusLandscapePrototype : MonoBehaviour
    {
        const int Lanes = 12; const float TopY = 315, HitY = -285, Travel = 2.1f;
        const float LaneWidth = 92f, NoteHeight = 31f;
        readonly Color[] colors = { new(.27f,.73f,1f), new(.28f,.95f,.67f), new(1f,.72f,.22f), new(1f,.36f,.69f) };
        readonly List<Note> notes = new(); RectTransform stage; Text score, combo, judge; float time; int points, chain; bool running;
        void Awake(){Application.targetFrameRate=120;Screen.orientation=ScreenOrientation.LandscapeLeft;Build();Seed();}
        void Update(){if(!running)return;time+=Time.unscaledDeltaTime;Move();InputRead();}
        void InputRead(){if(Input.GetMouseButtonDown(0))Hit(Lane(Input.mousePosition));for(var i=0;i<Input.touchCount;i++)if(Input.GetTouch(i).phase==TouchPhase.Began)Hit(Lane(Input.GetTouch(i).position));}
        int Lane(Vector2 pos)=>Mathf.Clamp((int)(pos.x/Screen.width*Lanes),0,Lanes-1);
        void Hit(int lane){Note best=null;var d=float.MaxValue;foreach(var n in notes)if(!n.done&&n.lane==lane&&Mathf.Abs(n.at-time)<d){best=n;d=Mathf.Abs(n.at-time);}if(best==null||d>.11f){chain=0;Show("MISS",new(1,.34f,.55f));Refresh();return;}best.done=true;best.view.gameObject.SetActive(false);chain++;points+=d<.05f?1000:650;Show(d<.05f?"PERFECT":"GREAT",d<.05f?new(.55f,1,1):colors[2]);Refresh();}
        // p is linear chart time: visual perspective never changes note timing or scroll speed.
        void Move(){foreach(var n in notes){if(n.done)continue;var p=Mathf.Clamp01((n.at-time)/Travel);n.view.anchoredPosition=new(X(n.lane,p),Mathf.Lerp(HitY,TopY,p));n.view.sizeDelta=new(Mathf.Lerp(LaneWidth-8,34,p)*n.span,Mathf.Lerp(NoteHeight,12,p));if(time-n.at>.11f){n.done=true;n.view.gameObject.SetActive(false);chain=0;Show("MISS",new(1,.34f,.55f));Refresh();}}}
        float X(int lane)=>X(lane,0);
        float X(int lane,float phase)=>((lane+.5f)/Lanes-.5f)*Mathf.Lerp(Lanes*LaneWidth,260,phase);
        void Seed(){var p=new[]{1,4,7,10,2,5,8,11,0,3,6,9};for(var i=0;i<56;i++)Add(p[i%p.Length],2+i*.34f,i%11==7?2f:1f,i%7==4);}
        void Add(int lane,float at,float span,bool flick){var r=Panel(flick?"Flick Note":"Tap Note",stage,colors[(lane+(flick?2:0))%4],new(LaneWidth-8,NoteHeight),new(X(lane),TopY));Outline(r.gameObject,Color.white,2);if(flick){var t=Label("FLICK",r,10);Fill(t.rectTransform);}notes.Add(new Note{lane=lane,at=at,span=span,view=r});}
        void Build(){var g=new GameObject("Rhythm Canvas",typeof(Canvas),typeof(CanvasScaler),typeof(GraphicRaycaster));new GameObject("Event System",typeof(EventSystem),typeof(StandaloneInputModule));var c=g.GetComponent<Canvas>();c.renderMode=RenderMode.ScreenSpaceOverlay;var sc=g.GetComponent<CanvasScaler>();sc.uiScaleMode=CanvasScaler.ScaleMode.ScaleWithScreenSize;sc.referenceResolution=new(1920,1080);var root=g.GetComponent<RectTransform>();Panel("Soft navy",root,new(.035f,.06f,.18f),Vector2.zero,Vector2.zero,true);Background(root);stage=Panel("Flat Rhythm Stage",root,new(.10f,.13f,.28f,.9f),new(Lanes*LaneWidth,700),new(0,-10));Stage(stage);Hud(root);Start(root);}
        void Background(RectTransform root){for(var i=0;i<62;i++)Panel("Equalizer",root,i%5==0?new(.77f,.25f,1,.34f):new(.05f,.63f,1,.28f),new(12,24+(i*43%170)),new(-900+i*30,-255));for(var i=0;i<5;i++){var card=Panel("Floating jacket",root,new(.25f,.15f,.52f,.35f),new(245,145),new(-650+i*325,i%2==0?190:105));Outline(card.gameObject,new(.8f,.29f,.95f,.45f),3);}}
        void Stage(RectTransform root){for(var i=0;i<=Lanes;i++){var lane=Panel("Perspective lane",root,new(.72f,.77f,1,.43f),new(3,1),Vector2.zero);Line(lane,new(((float)i/Lanes-.5f)*260,TopY),new(((float)i/Lanes-.5f)*Lanes*LaneWidth,HitY));}for(var i=0;i<8;i++){var p=i/7f;Panel("Beat grid",root,new(.65f,.7f,1,.18f),new(Mathf.Lerp(Lanes*LaneWidth,260,p),2),new(0,Mathf.Lerp(HitY,TopY,p)));}var hit=Panel("Judgment",root,new(.88f,.3f,1),new(Lanes*LaneWidth+14,10),new(0,HitY));Outline(hit.gameObject,new(.68f,.72f,1),3);for(var i=0;i<Lanes;i++){var pad=Panel("Touch "+i,root,new(colors[i%4].r,colors[i%4].g,colors[i%4].b,.15f),new(LaneWidth-6,72),new(X(i),-370));Outline(pad.gameObject,colors[i%4],2);}}
        void Hud(RectTransform root){var sp=Panel("Score card",root,new(.25f,.29f,.50f,.94f),new(430,120),new(-585,410));Outline(sp.gameObject,new(.78f,.82f,1,.85f),3);score=Label("SCORE\n0000000",sp,34);score.rectTransform.offsetMin=new(22,8);score.rectTransform.offsetMax=new(-10,-8);var lp=Panel("Life card",root,new(.25f,.29f,.50f,.94f),new(370,120),new(625,410));Outline(lp.gameObject,new(.78f,.82f,1,.85f),3);var life=Label("LIFE  1000\n━━━━━━━━━━━━",lp,27);life.color=new(.37f,1,.65f);Fill(life.rectTransform);var cp=Panel("Combo card",root,new(.31f,.22f,.51f,.95f),new(150,105),new(0,75));Outline(cp.gameObject,new(.98f,.61f,1),3);combo=Label("COMBO\n0",cp,27);Fill(combo.rectTransform);judge=Label("",root,46);judge.rectTransform.sizeDelta=new(540,80);judge.rectTransform.anchoredPosition=new(0,-350);var settings=Panel("Play settings",root,new(.18f,.22f,.42f,.9f),new(480,45),new(0,425));var settingText=Label("SPEED 8.0    WIDTH 100%    VIEW PERSPECTIVE    LINEAR",settings,16);Fill(settingText.rectTransform);}
        void Start(RectTransform root){var b=Panel("Start",root,new(.1f,.72f,.84f),new(330,92),new(0,-100));b.GetComponent<Image>().raycastTarget=true;Outline(b.gameObject,Color.white,3);var text=Label("開始試玩",b,32);Fill(text.rectTransform);b.gameObject.AddComponent<Button>().onClick.AddListener(()=>{b.gameObject.SetActive(false);running=true;Show("READY",Color.white);});}
        void Show(string v,Color c){judge.text=v;judge.color=c;}void Refresh(){score.text="SCORE\n"+points.ToString("0000000");combo.text="COMBO\n"+chain;}
        static RectTransform Panel(string n,RectTransform p,Color c,Vector2 s,Vector2 pos,bool stretch=false){var g=new GameObject(n,typeof(RectTransform),typeof(Image));var r=g.GetComponent<RectTransform>();r.SetParent(p,false);g.GetComponent<Image>().color=c;if(stretch){r.anchorMin=Vector2.zero;r.anchorMax=Vector2.one;r.offsetMin=Vector2.zero;r.offsetMax=Vector2.zero;}else{r.sizeDelta=s;r.anchoredPosition=pos;}return r;}static Text Label(string x,RectTransform p,int s){var g=new GameObject("Text",typeof(RectTransform),typeof(Text));var t=g.GetComponent<Text>();t.rectTransform.SetParent(p,false);t.text=x;t.font=Resources.GetBuiltinResource<Font>("LegacyRuntime.ttf");t.fontSize=s;t.fontStyle=FontStyle.Bold;t.alignment=TextAnchor.MiddleCenter;t.color=Color.white;return t;}static void Fill(RectTransform r){r.anchorMin=Vector2.zero;r.anchorMax=Vector2.one;r.offsetMin=Vector2.zero;r.offsetMax=Vector2.zero;}static void Outline(GameObject g,Color c,int w){var o=g.AddComponent<Outline>();o.effectColor=c;o.effectDistance=new(w,-w);}static void Line(RectTransform r,Vector2 a,Vector2 b){var d=b-a;r.sizeDelta=new(3,d.magnitude);r.anchoredPosition=(a+b)*.5f;r.localRotation=Quaternion.Euler(0,0,-Mathf.Atan2(d.x,d.y)*Mathf.Rad2Deg);}sealed class Note{public int lane;public float at,span;public bool done;public RectTransform view;}
    }
}
